"""Self-host the three Google Fonts families so the site has no runtime dependency
on fonts.googleapis.com. Downloads the woff2 files into assets/fonts/ and writes
assets/fonts/fonts.css with the @font-face rules rewritten to local paths.

Run once (and again only if the type stack changes):  python tools/fetch_fonts.py
"""
import os, re, sys, urllib.request

ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "assets", "fonts")
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Bodoni+Moda:ital,opsz,wght@0,6..96,400;0,6..96,600;1,6..96,400"
           "&family=Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;0,6..72,500;1,6..72,300"
           "&family=Archivo+Narrow:wght@400;600&display=swap")
# a modern UA makes Google serve variable woff2 with unicode-range subsets
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36"

def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()

os.makedirs(OUT, exist_ok=True)
css = get(CSS_URL).decode("utf-8")

# keep only the latin + latin-ext subsets; the site is English
blocks = re.findall(r"(/\* ([\w-]+) \*/\s*@font-face \{.*?\})", css, re.S)
kept, n, seen = [], 0, {}          # seen: url -> local file; Google repeats one variable file per weight
for block, subset in blocks:
    if subset not in ("latin", "latin-ext"):
        continue
    fam = re.search(r"font-family: '([^']+)'", block).group(1).replace(" ", "")
    style = re.search(r"font-style: (\w+)", block).group(1)
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    if url not in seen:
        name = f"{fam}-{style}-{subset}.woff2"
        path = os.path.join(OUT, name)
        if not os.path.exists(path):
            open(path, "wb").write(get(url)); n += 1
        seen[url] = name
    kept.append(block.replace(url, seen[url]))

open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8").write(
    "/* Generated by tools/fetch_fonts.py — self-hosted Google Fonts (OFL). Do not edit by hand. */\n"
    + "\n".join(kept) + "\n")
print(f"{len(kept)} @font-face rules, {n} new files -> {OUT}")
